# Generated by Django 4.2.9 on 2025-11-06 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='attributes',
            field=models.TextField(blank=True, help_text='Manual attributes from form', null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='csv_data',
            field=models.TextField(blank=True, help_text='Stored CSV recipients data as JSON', null=True),
        ),
    ]
