# Generated by Django 4.2.9 on 2025-11-07 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0002_campaign_attributes_campaign_csv_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Exact time when campaign finished/completed', null=True),
        ),
    ]
