# Generated by Django 4.2.9 on 2025-11-07 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0004_alter_emaillog_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BounceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=500)),
                ('bounce_reason', models.TextField(blank=True)),
                ('from_addr', models.CharField(blank=True, max_length=500)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('email_log', models.ForeignKey(blank=True, help_text='Linked EmailLog entry if matched', null=True, on_delete=django.db.models.deletion.SET_NULL, to='email_app.emaillog')),
            ],
            options={
                'ordering': ['-detected_at'],
                'unique_together': {('recipient_email', 'detected_at')},
            },
        ),
    ]
