# Generated by Django 4.2.9 on 2025-11-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0005_bouncerecord'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='bouncerecord',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='bouncerecord',
            name='detected_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='bouncerecord',
            name='recipient_email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AddIndex(
            model_name='bouncerecord',
            index=models.Index(fields=['recipient_email', '-detected_at'], name='email_app_b_recipie_92577b_idx'),
        ),
    ]
