# Generated by Django 4.2.9 on 2025-11-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0003_campaign_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed'), ('bounce', 'Bounce')], default='sent', max_length=20),
        ),
    ]
